version: '3.8'

services:
  database:
    build:
      context: ./database
    environment:
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3306:3306"

  web:
    build:
      context: ./sitioweb
    ports:
      - "80:80"
    depends_on:
      - database

volumes:
  db-data:
