version: '3.8'

services:
  db:
    build:
      context: ./database
    environment:
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"

  sitio:
    build:
      context: ./sitio
    ports:
      - "8080:80"
    depends_on:
      - db
