version: '3.8'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example

  web:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./sitioweb:/usr/share/nginx/html
