version: '3.8'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3306:3306"

  sitio:
    build:
      context: ./sitio   # Ruta al directorio donde se encuentra el Dockerfile del sitio
    ports:
      - "8080:80"   # Mapeo de puertos del contenedor
    depends_on:
      - db   # Dependencia del servicio de base de datos

